PARSE_SRCS = ../../solution/philo/parse.c ../../solution/philo/error.c

parse-test.exe: parse-test.c $(PARSE_SRCS) ../../solution/philo/philo.h
	cc -g parse-test.c $(PARSE_SRCS) -I../../solution/philo -o parse-test.exe